name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn release -- --ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
